### PR TITLE
Use module `field` in queries instead of hardcoded 'state'

### PR DESCRIPTION
**Pull request by elbasti**

### CODE REVIEW

**Comment by joaomdmoura** [comment]
Hello, @elbasti! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/joaomdmoura/machinery/pulls/53). Please check our [documentation](https://docs.ebertapp.io) for more information.

**Comment by joaomdmoura** [comment]
@elbasti thanks for the PR, this looks solid, I'll try to do some testing before merging it, but it was a good catch!
I wonder if there is a way you could include some testing to make sure silly me don't break it in the future :sweat_smile:

**Comment by elbasti** [comment]
@joaomdmoura sorry I took so long to look at this. I spent a few hours today trying to write tests but i'm hitting a wall. The issue is that the tests use `MachineryTest.TestRepo`, where `repo.all(query)` doesn't actually evaluate the query's `where` clause, so it doesn't catch the error. 

I actually have no idea how to test this.

**Comment by joaomdmoura** [comment]
np, thanks for giving it a try, I'll check it as well to see if I can figure something out before merging it

**Comment by joaomdmoura** [comment]
@elbasti this is fixed in the lib itself, but I'm dropping the dashboard in the next version so we won't need this change in there. Thank you so much for putting this together back then 🙇

**Pull request closed without merging**
