### PR TITLE
correct dashboard link

### PR DESCRIPTION
**Pull request by bgentry**

### CODE REVIEW

**Comment by joaomdmoura** [comment]
Hello, @bgentry! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/joaomdmoura/machinery/pulls/36). Please check our [documentation](https://docs.ebertapp.io) for more information.

**Comment by joaomdmoura** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 5 possible new issues (including those that may have been commented here).

You can see more details about this review at https://ebertapp.io/github/joaomdmoura/machinery/pulls/36.

**Comment by bgentry** [comment]
> Coverage increased (+41.9%) to 98.925%

not likely :joy:

**Comment by joaomdmoura** [comment]
haha @bgentry thanks for helping out! thank you so much!
The ebert issues are totally unrelated, I'll need to address that in another PR :sweat_smile:

**Pull request merged**
